steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fluidly-test', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/fluidly-test']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'fluidly-test', '--image', 'gcr.io/$PROJECT_ID/fluidly-test', '--region', 'europe-west1','--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/fluidly-test
